on: [push]

jobs:
  minify:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: check out the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: auto minify the files
        uses: nizarmah/auto-minify@v3
        with:
          overwrite: true
          js_engine: 'babel'

      - name: stash the changes, change to release branch, and unstash changes
        run: |
          git stash
          git checkout -b release
          git stash pop

      - name: auto commit the minified files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "bot: Add auto minified files"
          branch: "release"
          push_options: '--force'
